### ISSUE TITLE
Complete records not being loaded in the sync

### ISSUE THREAD

**Issue by nickkeenan** [karpet/action-network-run4something-sync#4]
Currently a maximum of 4700 records are being synced.  Not sure if this is an arbitrary limit for testing, or if we're hitting a constraint in (most likely) the Google Sheets API.  There should be around 8543 candidates, 403 tagged one-on-one and 395 both.

**Comment by nickkeenan** [comment]
Looks like we might be hitting the Google Sheet limit of 2 million cells?  Whee!  I'm working with Run 4 something to identify less critical columns which could open up the row limitations.

**Comment by karpet** [comment]
fixed in the fork
